version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: localhost
    init: true
    restart: "unless-stopped"
    volumes:
      - ./data/systems:/data/Data/systems
      - ./data/modules:/data/Data/modules
      - ./data/worlds:/data/Data/worlds
    environment:
      - CONTAINER_PRESERVE_OWNER=/data/Data/systems/.*\|/data/Data/modules/.*\|/data/Data/worlds/.*
    ports:
      - 30000:30000
    secrets:
      - source: config_json
        target: config.json
